language: node_js
node_js:
  - "stable"
  - "4"
  - "5"
  - "6"
  - "7"
  
install: "npm install mocha@latest supertest@latest --save-dev"  
script: "npm run test"
#after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"