language: node_js
node_js:
  - "stable"
  - "4.0.0"
  - "5.0.0"
  - "6.0.0"
  
install: "npm install mocha@latest supertest@latest -g"  
script: "npm run test"
#after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"